# Generated by Django 4.2.4 on 2023-08-12 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name of the exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('born_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('traineeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout_api.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.SmallIntegerField()),
                ('repetitions', models.SmallIntegerField()),
                ('exerciseId', models.ManyToManyField(to='workout_api.exercise')),
                ('workoutId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout_api.workout')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='involved_muscles',
            field=models.ManyToManyField(to='workout_api.muscle'),
        ),
    ]
