# Generated by Django 4.2.4 on 2023-08-12 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='born_date',
            new_name='birth_date',
        ),
        migrations.AddField(
            model_name='set',
            name='comments',
            field=models.CharField(default=datetime.datetime(2023, 8, 12, 14, 5, 44, 672762, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
