# Generated by Django 4.2.7 on 2023-11-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0002_rename_born_date_trainee_birth_date_set_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='is_bodyweight',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
